L16
Osshrp/tutu pull request #2
Opened 2017-04-05 11:23 UTC by Osshrp

2017-04-05 23:59 UTC, vkurennov requested changes

2017-04-05 23:59 UTC, vkurennov commented on app/controllers/carriages_controller.rb
> +    @carriage = class_name(params["class_id"]).constantize.new(carriage_params)
Можно и так, конечно, но это криво, если честно. Гораздо лучшен привести все к базовому классу, ведь в случае  STI он имеет все атрибуты всех потомков. А для этого пригодится метод `becomes`

2017-04-05 23:59 UTC, vkurennov commented on app/helpers/carriages_helper.rb
> +      'FirstClassCarriage' => 'first_class_carriage',
Ну для таких вещей совсем не обязательно делать хеш. Есть замечательный метод `underscore`,  который делат как раз то, что нужно.

2017-04-05 23:59 UTC, vkurennov commented on app/models/carriage.rb
> +    self.car_type = car_types[self.class.to_s]
А зачем тебе хранить еще и атрибут car_type, почему не достаточно type, в котором и будет записан класс в случае STI? Ну а если надо получить человекочитаемое название, то из хеша брать по типу значение

2017-04-05 23:59 UTC, vkurennov commented on app/models/carriage.rb
> +    self.number ||= carriages.map { |car| car.number.to_i }.max + 1
Зачем загружать все вагоны из базы и перебирать их? Гораздо лучше сразу на базу переложить работу по поиску максимального номера вагона. Для этого есть метод `maximum`.

2017-04-05 23:59 UTC, vkurennov commented on app/models/couch_carriage.rb
> +class FirstClassCarriage < Carriage
Имя файла и модели не совпадают, рельсы сделают за это больно в нужный момент.

2017-04-06 06:43 UTC, Osshrp commented on app/models/carriage.rb
> +    self.number ||= carriages.map { |car| car.number.to_i }.max + 1
Не знал, спасибо за науку :)

2017-04-06 06:45 UTC, Osshrp commented on app/models/carriage.rb
> +    self.car_type = car_types[self.class.to_s]
Осталось с прошлой реализации, сначала поленился переделать, оставил на потом, ведь работало, а потом забыл.

2017-04-06 06:49 UTC, Osshrp commented on app/helpers/carriages_helper.rb
> +      'FirstClassCarriage' => 'first_class_carriage',
Ок, спасибо.

2017-04-06 06:51 UTC, Osshrp commented on app/controllers/carriages_controller.rb
> +    @carriage = class_name(params["class_id"]).constantize.new(carriage_params)
Понял. А я ведь becomes в одном месте уже использовал. А тут не догадался.

2017-04-06 10:16 UTC, webmstk commented on app/models/railway_station.rb
> +    station_in_route = self.railway_stations_routes.where(route: route).first
станция может быть и не найдена, хорошо бы не падать при этом

2017-04-06 10:16 UTC, webmstk commented on app/models/train.rb
> +  def ordered(carriages)
можно в виде скоупа оформить

2017-04-06 10:16 UTC, webmstk commented on app/views/carriages/_form.html.slim
> +                                            ['сидячий', 'CouchCarriage']]))
места лучше в константах хранить

2017-04-06 10:34 UTC, Osshrp commented on app/models/train.rb
> +  def ordered(carriages)
Ну, как бы я так в виде скоупа оформил
Если true to вызыватеся скоуп asc_ordered, если нет то desc_ordered

2017-04-06 10:48 UTC, webmstk commented on app/models/train.rb
> +  def ordered(carriages)
Угу, видел. Но никто не запрещает вызывать скоуп в скоупе ) Удобно, когда такие вещи рядом

2017-04-06 11:01 UTC, Osshrp commented on app/models/train.rb
> +  def ordered(carriages)
А в скоупе можно условие проверить?

2017-04-06 11:12 UTC, Osshrp commented on app/models/railway_station.rb
> +    station_in_route = self.railway_stations_routes.where(route: route).first
Понял

2017-04-06 11:13 UTC, webmstk commented on app/models/train.rb
> +  def ordered(carriages)
я бы эту сортировку сделал ответственностью вагонов, а не поезда
```
scope :ordered, -> { train.sort? ? asc_ordered : desc_ordered }
```
потому что вызов `@train.ordered(@train.carriages)` выглядит непонятнее, чем `@train.carriages.ordered`

2017-04-06 11:30 UTC, Osshrp commented on app/models/train.rb
> +  def ordered(carriages)
Хм.. вроде выглядит красиво, но скоуп это же метод класса, там на момент вызова еще нет объекта train, или я не прав?

2017-04-06 11:33 UTC, Osshrp commented on app/models/train.rb
> +  def ordered(carriages)
А в него объект можно передавать?

2017-04-06 11:37 UTC, Osshrp commented on app/models/train.rb
> +  def ordered(carriages)
Так вроде нашел, что можно

2017-04-06 11:38 UTC, webmstk commented on app/models/train.rb
> +  def ordered(carriages)
надо проверить ) по поводу поезда, по-моему, ты прав
А вообще скоупы можно цеплять на Relation-ы, не только к классу. Вот это должно сработать:
```
scope :ordered, ->(sort) { sort ? asc_ordered : desc_ordered }
@train.carriages.ordered(train.sort)
```

2017-04-06 11:44 UTC, Osshrp commented on app/models/train.rb
> +  def ordered(carriages)
Супер, заработало !
Спасибо, Паша

2017-04-06 11:46 UTC, Osshrp commented on app/models/train.rb
> +  def ordered(carriages)
Нет, все верно, твой первый вариант рабочий, я проверил

2017-04-06 11:46 UTC, Osshrp commented on app/models/train.rb
> +  def ordered(carriages)
:+1:

2017-04-06 12:04 UTC, webmstk commented on app/models/train.rb
> +  def ordered(carriages)
ну отлично )

2017-04-06 12:51 UTC, Osshrp commented on app/views/carriages/_form.html.slim
> +                                            ['сидячий', 'CouchCarriage']]))
Был у меня метод car_type, который возвращал хэш, где ключами были названия слассов вагонов, а значением человеческое значение типов вагонов.
Решил сделать хзш костанту вместо метода и в селекте тоже ее использовать.
сделал вот такую кострукцию:
f.select(:type, options_for_select(Carriage::CAR_TYPE.to_a.map(&:reverse)))
И вот не знаю, хорошо ли это в виде держать? или метод создать в модели, который это будет делать?

2017-04-06 15:35 UTC, webmstk commented on app/views/carriages/_form.html.slim
> +        options_from_collection_for_select(Carriage::CAR_TYPES, :first, :last)
кажется, я узнал ещё круче вариант )
```
f.collection_select :type, Carriage::CAR_TYPES, :first, :last
```

2017-04-06 15:43 UTC, Osshrp commented on app/views/carriages/_form.html.slim
> +        options_from_collection_for_select(Carriage::CAR_TYPES, :first, :last)
Да, работает, супер!

2017-04-06 15:52 UTC, Osshrp commented on app/views/carriages/_form.html.slim
> +        options_from_collection_for_select(Carriage::CAR_TYPES, :first, :last)
Странно, но почему то в документации я не нашел ничего про :first, :last

2017-04-06 16:02 UTC, webmstk commented on app/views/carriages/_form.html.slim
> +        options_from_collection_for_select(Carriage::CAR_TYPES, :first, :last)
Я уже писал об этом. Это названия сообщений, которые будут посылаться первому аргументу (точнее элементу коллекции), чтобы получить значение. Например, можно сделать селект для Статей:
```
f.collection_select :article, Article.all, :id, :title
```
сгенерятся опшны, где значением будет id статьи, а текстом - название.

2017-04-06 16:08 UTC, webmstk commented on app/views/carriages/_form.html.slim
> +        options_from_collection_for_select(Carriage::CAR_TYPES, :first, :last)
в твоём примере можно было и так написать `Carriage::CAR_TYPES, :first, :second` за кулисами происходит примерно следующее
```
<option value="<%= ['FirstClassCarriage', 'св'].first %>">
  <%= ['FirstClassCarriage', 'св'].second %>
<option>
```

2017-04-06 16:10 UTC, Osshrp commented on app/views/carriages/_form.html.slim
> +        options_from_collection_for_select(Carriage::CAR_TYPES, :first, :last)
Да, я помню и документации это есть.
Я говорил про :first, :last.
Ведь :id, :tilte это, как я понимаю, названия полей в коллекции Article.all,
а вот :first, :last, я так понял .first и .last массива. Только  в доке рельсы про это ни слова :)

2017-04-06 16:11 UTC, Osshrp commented on app/views/carriages/_form.html.slim
> +        options_from_collection_for_select(Carriage::CAR_TYPES, :first, :last)
Ага, пока я писал, ты уже прислал)

2017-04-06 16:13 UTC, webmstk commented on app/views/carriages/_form.html.slim
> +        options_from_collection_for_select(Carriage::CAR_TYPES, :first, :last)
Пока ты так понимаешь, ты понимаешь неправильно ) Это не названия полей, это сообщения, посылаемые объекту. Возможно, так будет понятнее
```
<option value="<%= ['FirstClassCarriage', 'св'].send(:first) %>">
  <%= ['FirstClassCarriage', 'св'].send(:second) %>
<option>
```
и
```
<option value="<%= article.send(:id) %>">
  <%= article.send(:title) %>
<option>
```

2017-04-06 16:17 UTC, Osshrp commented on app/views/carriages/_form.html.slim
> +        options_from_collection_for_select(Carriage::CAR_TYPES, :first, :last)
Понял, понял, понял)
это название метода, который send посылает, а уж что это будет за метод зависит от принимающего объекта )

2017-04-06 16:19 UTC, webmstk commented on app/views/carriages/_form.html.slim
> +        options_from_collection_for_select(Carriage::CAR_TYPES, :first, :last)
Ну да. Тут просто важно понимать, что это необязательно должна быть модель или хеш, это может быть любая произвольная коллекция, элементы которой должны отвечать на посылаемые ей сообщения.

2017-04-06 16:20 UTC, Osshrp commented on app/views/carriages/_form.html.slim
> +        options_from_collection_for_select(Carriage::CAR_TYPES, :first, :last)
получается что можно туда вообще любой объект положить, главное, чтоб его метод возвращал то что нам нужно

2017-04-06 16:21 UTC, webmstk commented on app/views/carriages/_form.html.slim
> +        options_from_collection_for_select(Carriage::CAR_TYPES, :first, :last)
в общем, я вижу, ты понял :)

2017-04-06 16:21 UTC, webmstk commented on app/views/carriages/_form.html.slim
> +        options_from_collection_for_select(Carriage::CAR_TYPES, :first, :last)
но это должен быть итерируемый объект )

2017-04-06 16:23 UTC, Osshrp commented on app/views/carriages/_form.html.slim
> +        options_from_collection_for_select(Carriage::CAR_TYPES, :first, :last)
Спасибо, Паша!

2017-04-06 16:24 UTC, webmstk commented on app/views/carriages/_form.html.slim
> +        options_from_collection_for_select(Carriage::CAR_TYPES, :first, :last)
не за что )

2017-04-07 06:18 UTC, merged